groups:
- jobs:
  - bump-major
  - bump-minor
  - verify
  - build-deploy
  name: build-release
jobs:
- build_log_retention:
    builds: 1
  name: bump-minor
  plan:
  - get: release-version
    params:
      bump: minor
  - params:
      file: release-version/version
    put: release-version
  serial_groups:
  - release-version
- build_log_retention:
    builds: 1
  name: bump-major
  plan:
  - get: release-version
    params:
      bump: major
  - params:
      file: release-version/version
    put: release-version
  serial_groups:
  - release-version
- build_log_retention:
    builds: 10
  name: verify
  plan:
  - in_parallel:
    - get: amazon-kinesis-client-pullrequest
      trigger: true
      version: every
    - get: release-version
      params:
        bump: patch
    - get: pipeline-task
  - params:
      path: amazon-kinesis-client-pullrequest
      status: pending
    put: amazon-kinesis-client-pullrequest
  - file: pipeline-task/maven-v2/tasks/maven-dind-build.yml
    input_mapping:
      repo: amazon-kinesis-client-pullrequest
      version: release-version
    on_failure:
      params:
        path: amazon-kinesis-client-pullrequest
        status: failure
      put: amazon-kinesis-client-pullrequest
    on_success:
      params:
        path: amazon-kinesis-client-pullrequest
        status: success
      put: amazon-kinesis-client-pullrequest
    params:
      MAVEN_PHASES: verify
      MAVEN_USE_VERSIONS_PLUGIN: true
      NEXUS_PASSWORD: ((nexus-password}}
      NEXUS_USER: ((nexus-user}}
    privileged: true
    task: maven-build
- build_log_retention:
    builds: 5
  name: build-deploy
  plan:
  - in_parallel:
    - get: amazon-kinesis-client-git
      trigger: true
    - get: pipeline-task
    - get: release-version
      params:
        bump: patch
  - file: pipeline-task/maven-v2/tasks/maven-dind-build.yml
    input_mapping:
      repo: amazon-kinesis-client-git
      version: release-version
    on_failure:
      params:
        body_text: ${ATC_EXTERNAL_URL}/teams/main/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}
        subject_text: 'BUILD FAILED: ${BUILD_PIPELINE_NAME} - ${BUILD_JOB_NAME}/${BUILD_NAME}'
      put: send-email
    on_success:
      params:
        body_text: ${ATC_EXTERNAL_URL}/teams/main/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}
        subject_text: 'BUILD SUCCESS: ${BUILD_PIPELINE_NAME} - ${BUILD_JOB_NAME}/${BUILD_NAME}'
      put: send-email
    params:
      MAVEN_GOALS: deploy
      MAVEN_USE_VERSIONS_PLUGIN: true
      NEXUS_PASSWORD: ((nexus-password}}
      NEXUS_USER: ((nexus-user}}
    privileged: true
    task: maven-build
  - in_parallel:
    - params:
        file: release-version/version
      put: release-version
    - params:
        only_tag: true
        repository: amazon-kinesis-client-git
        tag: release-version/version
      put: amazon-kinesis-client-git
  - params:
      name: release-version/version
      tag: release-version/version
    put: github-release
  serial: true
resource_types:
- name: pull-request
  source:
    aws_access_key_id: ((aws-access-key))
    aws_secret_access_key: ((aws-secret-key))
    repository: 212136148154.dkr.ecr.ap-southeast-2.amazonaws.com/mirrored/docker.io/teliaoss/github-pr-resource
  type: docker-image
- name: email
  source:
    aws_access_key_id: ((aws-access-key))
    aws_secret_access_key: ((aws-secret-key))
    repository: 212136148154.dkr.ecr.ap-southeast-2.amazonaws.com/mirrored/docker.io/pcfseceng/email-resource
  type: docker-image
resources:
- icon: email
  name: send-email
  source:
    from: concourse@eroad.com
    smtp:
      host: email-smtp.us-west-2.amazonaws.com
      password: ((smtp-password))
      port: '587'
      username: ((smtp-username))
    to:
    - developers@eroad.co.nz
  type: email
- check_every: 10s
  icon: github
  name: amazon-kinesis-client-git
  source:
    branch: master
    ignore_paths:
    - ci/*
    - README.md
    password: ((github-password}}
    uri: https://github.com/eroad/amazon-kinesis-client.git
    username: ((github-username}}
  type: git
- check_every: 10s
  name: amazon-kinesis-client-pullrequest
  source:
    access_token: ((github-token}}
    base_branch: master
    ignore_paths:
    - ci/*
    - README.md
    repository: eroad/amazon-kinesis-client
  type: pull-request
- name: pipeline-task
  source:
    branch: master
    password: ((github-password}}
    uri: https://github.com/eroad/pipeline-task.git
    username: ((github-username}}
  type: git
- name: release-version
  source:
    access_key_id: ((aws-access-key}}
    bucket: eroad-artifact-ap-southeast-2
    initial_version: 1.7.0
    key: application-ci/amazon-kinesis-client/version/version
    region_name: ap-southeast-2
    secret_access_key: ((aws-secret-key}}
  type: semver
- icon: github
  name: github-release
  source:
    access_token: ((github-token}}
    repository: amazon-kinesis-client
    user: eroad
  type: github-release
